/* This file was autogenerated. Do not edit! */
#ifndef _INCL_MOJOSHADER_VERSION_H_
#define _INCL_MOJOSHADER_VERSION_H_
#define MOJOSHADER_VERSION -1
#define MOJOSHADER_CHANGESET "git-fe0be727cadd7b2976c56206af6dad0c8f4df859"
#endif

